FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="quast" \
software.version="5.0.2" \
about.summary="Perform quality assessment of genome assemblies using quast" \
about.home="https://github.com/ablab/quast"

ENV quast_version=5.0.2

ENV PACKAGES="wget parallel gcc g++ make perl libncurses5-dev zlib1g-dev libbz2-dev libfreetype6-dev libpng-dev"

ENV PYTHON="python3 python3-dev python3-pip"

ENV PYTHON_PACKAGES="matplotlib"

RUN apt-get update \
&& apt-get install -y $PACKAGES \
&& apt-get install -y $PYTHON \
&& pip3 install --no-cache-dir $PYTHON_PACKAGES \
&& wget https://github.com/ablab/quast/releases/download/quast_${quast_version}/quast-${quast_version}.tar.gz \
&& tar -xzf quast-${quast_version}.tar.gz \
&& cd quast-${quast_version} \
&& python3 setup.py install \
&& chmod +x quast.py \
&& cd .. \
&& mv quast-${quast_version} /usr/local/bin \
&& rm quast-${quast_version}.tar.gz

ENV PATH ${PATH}:/usr/local/bin/quast-${quast_version}

