FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="kraken2" \
software.version="2.0.8" \
about.summary="Taxonomic sequence classification using kraken2" \
about.home="https://github.com/DerrickWood/kraken2"

ENV kraken_version=2.0.8

RUN apt-get update && apt-get install -y gcc g++ wget parallel build-essential rsync unzip ncbi-blast+ \
&& wget https://github.com/DerrickWood/kraken2/archive/v${kraken_version}-beta.tar.gz \
&& tar -xzf v${kraken_version}-beta.tar.gz \
&& rm v${kraken_version}-beta.tar.gz \
&& cd kraken2-${kraken+version}-beta \
&& ./install_kraken2.sh /usr/local/bin

