FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="mykrobe" \
software.version="0.8.1" \
about.summary="Call antimicrobial resistance using mykrobe" \
about.home="https://github.com/Mykrobe-tools/mykrobe"

ENV mykrobe_version=0.8.1

ENV PACKAGES="wget parallel rsync git build-essential r-base-core zlib1g-dev libncurses5-dev libz-dev liblzma-dev libbz2-dev locales locales-all" \
PYTHON="python3.7 python3.7-dev python3-pip"

RUN apt-get update \
&& apt-get install -y $PACKAGES $PYTHON \
&& git clone --recursive -b geno_kmer_count https://github.com/phelimb/mccortex \
&& make -C mccortex \
&& mv mccortex /usr/local/bin \
&& wget -O mykrobe-${mykrobe_version}.tar.gz https://github.com/Mykrobe-tools/mykrobe/archive/v${mykrobe_version}.tar.gz \
&& tar -xzf mykrobe-${mykrobe_version}.tar.gz \
&& cd mykrobe-${mykrobe_version} \
&& pip3 install -r requirements.txt \
&& pip3 install . \
&& ln -s /usr/local/bin/mccortex/bin/mccortex31 /usr/local/lib/python3.7/dist-packages/mykrobe/cortex/mccortex31 \
&& wget -O /usr/local/bin/json_to_tsv.py https://raw.githubusercontent.com/iqbal-lab/Mykrobe-predictor/master/scripts/json_to_tsv.py \
&& chmod +x /usr/local/bin/json_to_tsv.py \
&& wget -O mykrobe-data.tar.gz http://s3.climb.ac.uk/mykrobe/mykrobe-data.tgz \
&& tar -zxf mykrobe-data.tar.gz \
&& mv mykrobe-data data \
&& cd data \
&& rsync -a * /usr/local/lib/python3.7/dist-packages/mykrobe/data/

RUN locale-gen en_GB.UTF-8
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8

ENV PATH ${PATH}:/usr/local/bin/mccortex/bin

