FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="multiqc" \
software.version="1.9" \
about.summary="Create a single report for multiple bioinformatics analyses using multiqc" \
about.home="https://github.com/ewels/MultiQC"

ENV pandoc_version=2.3 \
MultiQC_version=1.9

ENV PACKAGES="wget parallel make bzip2 gcc g++ libc6-dev libncurses-dev xz-utils zlib1g-dev libfreetype6 libpng-dev" \
PYTHON="python3 python3-dev python3-pip"

RUN apt-get update \
&& apt-get -y install $PACKAGES $PYTHON \
&& wget -O pandoc-${pandoc_version}-linux.tar.gz "https://github.com/jgm/pandoc/releases/download/${pandoc_version}/pandoc-${pandoc_version}-linux.tar.gz" \
&& tar -xzf pandoc-${pandoc_version}-linux.tar.gz -C /usr/local/bin \
&& find /usr/local/bin/pandoc-${pandoc_version} -name "pandoc" -exec ln -s {} /usr/local/bin \; \
&& wget -O MultiQC-${MultiQC_version}.tar.gz "https://github.com/ewels/MultiQC/archive/v${MultiQC_version}.tar.gz" \
&& tar -xzf MultiQC-${MultiQC_version}.tar.gz \
&& cd MultiQC-${MultiQC_version} \
&& python3 setup.py install
